In [6]:
import torch

In [5]:
num_inputs = 784
num_outputs = 10

In [7]:
W = torch.normal(0, 0.01, size = (num_inputs, num_outputs), 
                 requires_grad = True)
b = torch.zeros(num_outputs, requires_grad = True)

In [8]:
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [12]:
def soft_max(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim = True)
    return X_exp / partition

In [13]:
X = torch.normal(0, 1, (2, 5))
X_prob = soft_max(X)
X_prob, X_prob.sum(1, keepdim = True)

(tensor([[0.1816, 0.5856, 0.1174, 0.0445, 0.0709],
         [0.2529, 0.3125, 0.1871, 0.1668, 0.0807]]),
 tensor([[1.0000],
         [1.0000]]))

In [14]:
def net(X):
    return soft_max(torch.matmul(X.reshape((-1, W.shape[0])), W) + b)

In [15]:
def cross_entropy(y_hat, y):# y_hat是本次预测的,概率y是最终结果标签
    return - torch.log(y_hat[range(len(y_hat)), y])

In [16]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])